packages:
  - "apps/*"
  - "packages/*"
catalog:
  "@auth/core": 0.37.0
  "@convex-dev/auth": ^0.0.90
  "@oslojs/crypto": 1.0.1
  "@radix-ui/react-label": ^2.1.7
  "@tailwindcss/vite": ^4.1.16
  "@tanstack/react-router-devtools": 1.134.9
  "@tanstack/react-router": 1.134.9
  "@tanstack/react-start": ^1.134.9
  "@types/css-tree": ^2.3.11
  "@types/react-dom": ^19.2.2
  "@types/react": ^19.2.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  convex: ^1.28.2
  css-tree: ^3.1.0
  framer-motion: ^12.23.24
  howler: ^2.2.4
  input-otp: ^1.4.2
  jose: 6.1.0
  lucide-react: ^0.552.0
  radix-ui: ^1.4.3
  react-dom: ^19.2.0
  react-hook-form: ^7.66.0
  react: ^19.2.0
  recharts: ^3.3.0
  resend: 6.4.0
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.16
  tsup: ^8.5.0
  typescript: ~5.9.3
  vite: 7.1.12
  vitest: ^4.0.6
  zod: ^4.1.12
  zustand: ^5.0.8
