packages:
  - "apps/*"
  - "packages/*"
catalog:
  '@auth/core': ^0.37.0
  '@convex-dev/auth': ^0.0.90
  '@eslint/css-tree': 3.6.6
  '@oslojs/crypto': ^1.0.1
  '@radix-ui/react-label': ^2.1.8
  '@tailwindcss/vite': ^4.1.17
  '@tanstack/react-router': ^1.136.18
  '@tanstack/react-router-devtools': ^1.136.18
  '@tanstack/react-start': 1.137.0
  '@types/css-tree': ^2.3.11
  '@types/react': ^19.2.6
  '@types/react-dom': ^19.2.3
  b_short: ^3.1.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  convex: 1.29.3
  framer-motion: ^12.23.24
  howler: ^2.2.4
  input-otp: ^1.4.2
  jose: 6.1.2
  lucide-react: 0.554.0
  radix-ui: ^1.4.3
  react: ^19.2.0
  react-dom: ^19.2.0
  react-hook-form: 7.66.1
  recharts: 3.4.1
  resend: 6.5.2
  tailwind-merge: 3.4.0
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  vite: ^7.2.4
  zod: ^4.1.12
  zustand: ^5.0.8
