import { Project } from "ts-morph";
import { writeFileSync } from "fs";
import { resolve } from "path";

const project = new Project();
const sourceFiles = project.addSourceFilesAtPaths(
  resolve("packages/b_declarations/src/properties/**/definition.ts")
);

const irMap: Record<string, string> = {
  // Default custom property type
  [String.raw`\-\-${string}`]: "CustomPropertyIR"
};

sourceFiles.forEach((file) => {
  const defCalls = file.getVariableDeclarations()
    .filter(v => v.getName() === "property")
    .map(v => v.getInitializer());
    
  defCalls.forEach(defCall => {
    if (defCall?.getTypeArguments().length) {
      const typeArg = defCall.getTypeArguments()[0]?.getText();
      const propName = defCall.getArguments()[0]?.getText()?.replace(/['"]/g, "");
      if (typeArg && propName) {
        irMap[propName] = typeArg;
      }
    }
  });
});

const output = `// Auto-generated by generate-types-map.mts - DO NOT EDIT
export interface PropertyIRMap {
${Object.entries(irMap)
  .map(([k, v]) => `  "${k}": ${v};`)
  .join("\n")}
}
`;
writeFileSync(
  resolve("packages/b_declarations/src/types.map.ts"),
  output
);